### ISSUE TITLE
Rascal check crashed unexpectedly with: Cannot write TPL file |target://bas2-maintainability-model/rascal/$LoC.tpl|, reason: IO("-1: Cannot mkDirectory on a rascal uri: target://bas2-maintainability-model")at: |lib://rascal-core/lang/rascalcore/check/CheckerCommon.rsc|(9408,2,<243,61>,<243,63>)

### ISSUE THREAD

**Issue by BasRemmen** [usethesource/rascal-language-servers#548]
Not sure what the issue is here.

Exception thrown:
```
|lib://rascal-core/lang/rascalcore/check/CheckerCommon.rsc|:243,61: "Cannot write TPL file |target://bas2-maintainability-model/rascal/$LoC.tpl|, reason: IO(\"-1: Cannot mkDirectory on a rascal uri: target://bas2-maintainability-model\")"
```
Stacktrace:
```
	at removeTModel(|lib://rascal-core/lang/rascalcore/check/CheckerCommon.rsc|(9345,76,<242,25>,<244,9>))
	at removeOldestTModelFromCache(|lib://rascal-core/lang/rascalcore/check/CheckerCommon.rsc|(9638,28,<253,13>,<253,41>))
	at clearTModelCache(|lib://rascal-core/lang/rascalcore/check/CheckerCommon.rsc|(8547,32,<223,13>,<223,45>))
	at rascalTModelForLocs(|lib://rascal-core/lang/rascalcore/check/Checker.rsc|(14411,21,<337,11>,<337,32>))
	at check(|lib://rascal-core/lang/rascalcore/check/Checker.rsc|(19552,64,<475,9>,<475,73>))
	at $shell$(|main://$shell$|)

```

**Comment by DavyLandman** [comment]
@PaulKlint this one was solved right? With the upcoming rascal core release?

**Comment by PaulKlint** [comment]
I suspect it is caused by the target scheme that is not yet supported in the main branch.

**Comment by DavyLandman** [comment]
The target scheme has been around for a while, I thought this was a duplicate of #529 ?

**Comment by PaulKlint** [comment]
It is indeed a duplicate of #529.

One observation: `target://bas2-maintainability-model` should be `target:///bas2-maintainability-model` (but this does not solve the problem).
Other observation: `isDirectory(|target:///classes|)` yields false although it does exist.

My suspicion is still the `target` scheme.

**Comment by DavyLandman** [comment]
Target behaves like the project scheme, so it should have the project name in the authority. Target refers to the target folder in a specific project.

But we could have missed some cases in how the resolver behaves.

**Comment by PaulKlint** [comment]
More observations:

```
rascal>mkDirectory(|target://rascal-core/XX|);
ok
rascal>isDirectory(|target://rascal-core/XX|);
bool: true
```
BUT

the directory has been created in `|target://rascal-core/classes/XX|` !!

This explains at least why the `.tpl` file could not be written.

**Comment by PaulKlint** [comment]
@DavyLandman and I have played with scenario's to reproduce this. Here is one:
- Create a new directory `b_b_b` with a subdirectory `src` that contains a single file `M.rsc` (no `pom.xml`, no `META-INF/RASCAL.MF`).
- import `b_b_b` in a VSCode workspace.
- edit and then save `M.rsc`.

Result:
<img width="804" alt="Screenshot" src="https://github.com/user-attachments/assets/7fd91288-a0a8-429a-9e72-26a84dafed7e" />

After further analysis it turns out that -- in the absence of a manifest -- the project name is set to `""` and the target folder is set to` |target:///|`. This starts with `getProjectPathConfig` in `util::Reflective` but the error is further downstream and this has to be further explored.

**Comment by PaulKlint** [comment]
Further exploration by @sungshik has revealed that this problem is partly solved in the https://github.com/usethesource/rascal/tree/replace-lib-by-mvn-and-others-fix/std-always-from-current2 branch, albeit that in that branch also some NPEs are visible in the logs. Work in progress to  deal with them.
